/*
 * This file was written by Brian D. Smith, however, he considers it too
 * trifling to keep any rights to it. If you find it useful, good. If not, oh
 * well, it was useful to the author.  */

/*
 * This header file is for use with the functions defined in "alarm.c". See
 * that file for an explanation of use. */

#ifndef _ALARM_H_
#define _ALARM_H_

#include <signal.h>

#define SIGALRM 		14

#endif /* _ALARM_H_ */
