PROG=   batlstar.exe
SRCS=	batlstar.c comm1.c comm2.c comm3.c comm4.c comm5.c comm6.c comm7.c \
	init.c cypher.c getcom.c parse.c room.c save.c fly.c misc.c \
	globals.c dayfile.c nightfile.c dayobjs.c nightobjs.c words.c alarm.c

OBJS=	batlstar.obj comm1.obj comm2.obj comm3.obj comm4.obj comm5.obj comm6.obj comm7.obj \
	init.obj cypher.obj getcom.obj parse.obj room.obj save.obj fly.obj misc.obj \
	globals.obj dayfile.obj nightfile.obj dayobjs.obj nightobjs.obj words.obj alarm.obj

CFLAGS = -DMSDOS -mh -O2 -d

.c.obj:
	bcc -c $(CFLAGS) {$< }

$(PROG): $(OBJS)
	bcc $(CFLAGS) @&&|
$(OBJS) hcurses.lib
|

alarm.obj: alarm.c alarm.h
batlstar.obj: batlstar.c externs.h
comm1.obj: comm1.c externs.h
comm2.obj: comm2.c externs.h
comm3.obj: comm3.c externs.h
comm4.obj: comm4.c externs.h
comm5.obj: comm5.c externs.h
comm6.obj: comm6.c externs.h
comm7.obj: comm7.c externs.h
cypher.obj: cypher.c externs.h
dayfile.obj: dayfile.c externs.h
dayobjs.obj: dayobjs.c externs.h
fly.obj: fly.c externs.h alarm.h
getcom.obj: getcom.c externs.h
globals.obj: globals.c externs.h
init.obj: init.c externs.h
misc.obj: misc.c externs.h
nightfile.obj: nightfile.c externs.h
nightobjs.obj: nightobjs.c externs.h
parse.obj: parse.c externs.h
room.obj: room.c externs.h
save.obj: save.c externs.h
words.obj: words.c externs.h
